---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name postgresql
  namespace: database
spec:
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: "15.5.32"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    global:
      postgresql:
        auth:
          username: "tienk8srootuser"
          database: "keycloak"
          existingSecret: "database-credential"
          secretKeys:
            adminPasswordKey: "admin-password"
            userPasswordKey: "user-password"
            replicationPasswordKey: "replication-password"
