apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name strimzi-kafka-operator
  namespace: kafka
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: *name
      version: "0.43.0"
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
      interval: 5m
  releaseName: *name
  install:
    remediation:
      retries: 3