---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name kafka-ui
  namespace: kafka
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: *name
      version: "1.4.5"
      sourceRef:
        kind: HelmRepository
        name: kafbat
        namespace: flux-system
      interval: 5m
  releaseName: *name
  install:
    remediation:
      retries: 3
  values:
    env:
      - name: DYNAMIC_CONFIG_ENABLED
        value: 'true'
      - name: KAFKA_CLUSTERS_0_NAME
        value: 'caba-kafka-cluster'
      - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
        value: 'caba-kafka-cluster-kafka-bootstrap.kafka.svc:9093'
      - name: KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION
        value: '/etc/kafka/secrets/ca.p12'
      - name: KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD
        valueFrom:
          secretKeyRef:
            name: caba-kafka-cluster-cluster-ca-cert
            key: ca.password
      - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
        value: 'SSL'
      - name: KAFKA_CLUSTERS_0_SSL_KEYSTORELOCATION
        value: '/etc/kafka/secrets/user/user.p12'
      - name: KAFKA_CLUSTERS_0_SSL_KEYSTOREPASSWORD
        valueFrom:
          secretKeyRef:
            name: iamtienng
            key: user.password
    volumeMounts:
      - name: kafka-certs
        mountPath: "/etc/kafka/secrets"
        readOnly: true
      - name: kafka-user-secret
        mountPath: "/etc/kafka/secrets/user"
        readOnly: true
    volumes:
      - name: kafka-certs
        secret:
          secretName: caba-kafka-cluster-cluster-ca-cert
      - name: kafka-user-secret
        secret:
          secretName: iamtienng