---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app keycloakx
  namespace: flux-system
spec:
  targetNamespace: auth
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./gitops/infra/auth/keycloakx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
