# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app postgresql
#   namespace: flux-system
# spec:
#   targetNamespace: database
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   path: ./gitops/infra/database/postgresql/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
