---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app caba-kafka-cluster
  namespace: flux-system
spec:
  targetNamespace: kafka
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: strimzi-kafka-operator
  path: ./gitops/infra/kafka/kafka-cluster/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
