apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: iamtienng
  namespace: kafka
  labels:
    strimzi.io/cluster: caba-kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Read
          - Describe