apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    admin-password: ENC[AES256_GCM,data:NyDOlO0Bk4PA2Ij69TFA57Vfg1Q=,iv:1nPHYGYNHko13uit1KV1gt8ucpTH1pUnICS5btl+nOw=,tag:fKlskCgVNqJ28LQPWsHoqQ==,type:str]
    user-password: ENC[AES256_GCM,data:qeAS6dxUmCGPOJ3HUgkv+h9JDAM=,iv:yJn5uMtmlJJAECDUy/hyjjnj7nII4dVVGcPLqPgFxco=,tag:oyDenildkY3zayVbAu7qHg==,type:str]
    replication-password: ENC[AES256_GCM,data:imQ7dRr9b4F2SRjVTfVNxHIuIZ0=,iv:Xsv4Vqfs3yfWk246pv2HTjFlA/LVNsC3zeDJ5R+4Caw=,tag:q2nRrn7dtHLtKnuKkyn27Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4duwhqxrv2kwpt72l6ussm2dxawe6ky39w20mqx4pgttnshac2s5rnf6r
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS3AwV3RGVWhNa2t0UkR5
              T2J2eGZjbkYrcVdlWWRGdEY4NHd5RDVBaWhFCm9BakVwWXZvMmNUVEZpUjkxeXM3
              WmhSUmhQSURpNWtYdCtJcjB0ZTY0YjQKLS0tIGRSSDZldHluYkFKMXR4MkhXMHZH
              eFc0YWtqdkF0OXJ3ejZicGVlMTNQSUkKFnEJ7nuKbBFqnECTejQMtKD6kKArZxyZ
              FBZC9VgyyyjYBb23jTrtAehwPRd6T6G/9NbhCFfJUpvH3huIaiBNxw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T22:11:03Z"
    mac: ENC[AES256_GCM,data:NnRmBYQBZNEzb99/FQHVrnrQdCEG62mvUBvT5DjklENuZ+GBOVbudKVi5Ukb3QyuTNE7QcvStkwr+Jndil2Yk5KNofSKCsM4V9V1eSViNqPmCuC9NsSibtgndKQtGJ7YYFq8LdPQBnym108L4sHNg3iJO5lcnyToTYIanMQZAnI=,iv:uyY9UjVgnjOOAf+MctaKFDNiIRMG12IDXw1m2tDcm7k=,tag:iCE7i1tmio4m67VooJnBvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|token|values)$
    version: 3.9.0
